# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy WAR app to Azure Web App - azure-spring-test

on:
  push:
    branches:
      - "main"
    paths:
      - "backend/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_USER: springuser
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: tasks_db
          MYSQL_ROOT_PASSWORD: password

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4
      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Start Mysql container
        run: docker compose up -d

      - name: Build with Maven
        run: mvn clean package

      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: 'azure-spring-test'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4E686F89D448491CA9CA360EB840655C }}
          package: ${{ github.workspace }}/backend/target/*.jar

      - name: Run JAR on Azure Web App
        run: |
          echo "Current Working Directory:$(pwd)"
          ls -al /home/runner/work/azure-spring-test/azure-spring-test/backend/target
          java -debug -jar /home/runner/work/azure-spring-test/azure-spring-test/backend/target/azure-spring-test-0.0.1-SNAPSHOT.jar
